-- PRIMERA VERSIÓN DE LA SOLICITUD HECHA EL 31/03/20, FALTA COMPARAR COMPORTAMIENTOS EN PROSCAI

SELECT 
BCOD AS CUENTA,
BNOMBRE AS NOMBRE_CUENTA,
   PODESCR AS CONCEPTO,
   BATIP AS TM,
   BAOK AS OK, 
   POFAMILIA AS FAMILIA,
    POCHEQUE AS CHEQUE,
    PONUM AS PÓILIZA,
    BAIMPORNEG AS CARGOS,
    BAIMPOR AS ABONOS,
    BACENCOS AS CENTRO_COSTOS,
    POBENEF AS BENEFICIARIO,
    POCIA AS CIA,
    POUSR AS USR,
   POFECHA AS FECHA
    
     
    
FROM
    fbenc
        LEFT JOIN
    FBANMOV ON FBANMOV.BSEQ = FBENC.BSEQ
        LEFT JOIN
    FPOLIZA ON FPOLIZA.POSEQ = FBANMOV.POSEQ
WHERE
    POCIA <=3 AND 
    bcod = 1020101003

