SELECT MID(ICOD,1,9) AS 'MODELO PADRE',
ICOD AS MODELO,
IDESCR AS DESCRIPCION,

PLTALLA AS TALLA,
PLTALLA AS COLOR,
PLCANT AS CANTIDAD,
PENUM AS FOLIO,
PLPRECI AS PRECIO,
PEFECHA AS FECHA

 FROM FPLIN


LEFT JOIN FINV ON FINV.ISEQ=FPLIN.ISEQ

LEFT JOIN FPENC ON FPENC.PESEQ=FPLIN.PESEQ


WHERE (PLTIPMV='O'OR PLTIPMV='OC')

AND PEFECHA >'2020-08-21'
