select MID(ICOD,1,9)AS 'MODELO PADRE',
MID(ICOD,1,11)AS 'MODELO COLOR',
IDESCR AS DESCRIPCION,
FAM2.FAMDESCR AS DEPARTAMENTO,
SUM(ALMCANT)  AS INVENTARIO,
ROUND(ILISTA4 *1.16,2) AS COSTO,
ROUND(ILISTA4 *1.16 ,2) *  SUM(ALMCANT) AS 'COSTO TOTAL',
ILISTA1 AS PRECIO,
FAM1.FAMDESCR AS PROVEEDOR,
FAM3.FAMDESCR AS TIPO,
FAM4.FAMDESCR AS SUBTIPO,
FAM5.FAMDESCR AS PERSONAJE,
FAM6.FAMDESCR AS TRIMESTRE,
FAM7.FAMDESCR AS DISEÑADOR, 
FAM8.FAMDESCR AS LICENCIA, 
FAM9.FAMDESCR AS 'TIPO DE LICENCIA',
IF(CATDESCR='IBUSHAK/MERCADO LIBRE','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE TOXIC','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE FULL','MERCADO LIBRE',
IF(CATDESCR='AMAZON COMER','AMAZON',
IF(CATDESCR='AMAZON EN CEDIS','AMAZON',
IF(CATDESCR='ALMACEN B2B LEKRASH','SHOPIFY',
CATDESCR
)))))) AS TIENDA,
CATCONTACTO  AS 'CLASIFICACIÓN TIENDAS'





from FINV

LEFT JOIN FALM ON FALM.ISEQ = FINV.ISEQ
LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FALM.ALMNUM
LEFT JOIN FFAM AS FAM1 ON FAM1.FAMTNUM=FINV.IFAM1
LEFT JOIN FFAM AS FAM2 ON FAM2.FAMTNUM=FINV.IFAM2
LEFT JOIN FFAM AS FAM3 ON FAM3.FAMTNUM=FINV.IFAM3
LEFT JOIN FFAM AS FAM4 ON FAM4.FAMTNUM=FINV.IFAM4
LEFT JOIN FFAM AS FAM5 ON FAM5.FAMTNUM=FINV.IFAM5
LEFT JOIN FFAM AS FAM6 ON FAM6.FAMTNUM=FINV.IFAM6
LEFT JOIN FFAM AS FAM7 ON FAM7.FAMTNUM=FINV.IFAM7
LEFT JOIN FFAM AS FAM8 ON FAM8.FAMTNUM=FINV.IFAM8
LEFT JOIN FFAM AS FAM9 ON FAM9.FAMTNUM=FINV.IFAM9





 WHERE
                 ALMCANT > 0
AND (ALMNUM <> 0 AND ALMNUM <> 910  AND ALMNUM <> 911 AND ALMNUM <> 912 AND ALMNUM <> 913  AND ALMNUM <> 914 AND ALMNUM <> 915 AND ALMNUM <> 916 AND ALMNUM <> 917  AND ALMNUM <> 918 AND ALMNUM <> 920 AND ALMNUM <> 921 AND ALMNUM <> 923 AND ALMNUM <> 928 AND ALMNUM <> 930 AND ALMNUM <> 933 AND ALMNUM <> 934)


AND ITIPO = 1

            GROUP BY MID(ICOD,1,11),ALMNUM

ORDER BY ALMNUM