SELECT IEAN AS EAN,ICOD AS MODELO,
IDESCR AS DESCRIPCION,FAM2.FAMDESCR AS DEPARTAMENTO,
(ALMCANT-ALMASIGNADO)  AS INVENTARIO,ILISTA4 AS COSTO,ILISTA4 * ALMCANT AS COSTO_TOTAL,ILISTA1 AS PRECIO,
FAM1.FAMDESCR AS PROVEEDOR,FAM3.FAMDESCR AS TIPO,FAM4.FAMDESCR AS SUBTIPO,FAM5.FAMDESCR AS PERSONAJE,
FAM6.FAMDESCR AS TRIMESTRE,FAM7.FAMDESCR AS DISEÑADOR,FAM8.FAMDESCR AS LICENCIA, FAM9.FAMDESCR AS TIPO_DE_LICENCIA,
FAMA.FAMDESCR AS OFERTA, 
CATDESCR AS TIENDA,
CATCONTACTO  AS 'CLASIFICACIÓN TIENDAS',
MID(ICOD,1,9) AS 'MODELO PADRE',
IF(MID(ICOD,12,2)='','UN',MID(ICOD,12,2)) AS TALLA,
CONCAT(FAM2.FAMDESCR,'-',FAM3.FAMDESCR) AS CONCATENADO

from FINV

LEFT JOIN FALM ON FALM.ISEQ = FINV.ISEQ
LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FALM.ALMNUM
LEFT JOIN FFAM AS FAM1 ON FAM1.FAMTNUM=FINV.IFAM1
LEFT JOIN FFAM AS FAM2 ON FAM2.FAMTNUM=FINV.IFAM2
LEFT JOIN FFAM AS FAM3 ON FAM3.FAMTNUM=FINV.IFAM3
LEFT JOIN FFAM AS FAM4 ON FAM4.FAMTNUM=FINV.IFAM4
LEFT JOIN FFAM AS FAM5 ON FAM5.FAMTNUM=FINV.IFAM5
LEFT JOIN FFAM AS FAM6 ON FAM6.FAMTNUM=FINV.IFAM6
LEFT JOIN FFAM AS FAM7 ON FAM7.FAMTNUM=FINV.IFAM7
LEFT JOIN FFAM AS FAM8 ON FAM8.FAMTNUM=FINV.IFAM8
LEFT JOIN FFAM AS FAM9 ON FAM9.FAMTNUM=FINV.IFAM9
LEFT JOIN FFAM AS FAMA ON FAMA.FAMTNUM=FINV.IFAMA


where ALMCANT > 0
AND (ALMNUM <> 0 or ALMNUM <> 501)
AND ITIPO = 1

ORDER BY ALMNUM