SELECT
concat(ROUND(SUM(AIPRECIO*1.16*AICANTF),1),'|') AS PRECIO,
concat(DALMACEN,'|')  AS TIENDA,
CONCAT(SUM(AICANTF),'|') AS PIEZAS,
CONCAT(DFECHA,'|') AS FECHA,
MID(DHORA,11,9) AS HORA




FROM FAXINV


LEFT JOIN FDOC ON FDOC.DSEQ=FAXINV.DSEQ

LEFT JOIN FINV ON FINV.ISEQ=FAXINV.ISEQ

LEFT JOIN FCLI ON FCLI.CLISEQ=FDOC.CLISEQ

LEFT JOIN FUNIDAD ON FUNIDAD.UCOD=FINV.IUM

LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FDOC.DALMACEN

LEFT JOIN FAG ON FAG.AGTNUM = FDOC.DPAR1

WHERE DITIPMV='T' AND (DFECHA>='2020-03-24' AND DFECHA<='2020-03-24')

GROUP BY DNUM