SELECT CATDESCR AS TIENDA_VENTA,
CLINOM AS CLIENTE,
DMULTICIA AS COMPAÑIA,
SUM(DPAGO6) AS PUNTOS_USADOS


FROM FAXINV

LEFT JOIN FDOC ON FDOC.DSEQ=FAXINV.DSEQ

LEFT JOIN FINV ON FINV.ISEQ=FAXINV.ISEQ

LEFT JOIN FCLI ON FCLI.CLISEQ=FDOC.CLISEQ

LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FDOC.DALMACEN

/*EXCLUYE LAS TIENDAS DE MAYOREO Y BODEGAS

*/


WHERE DITIPMV='T'AND DALMACEN <> 301 AND DALMACEN <>302

/*RANGO DE FECHAS

*/
AND DFECHA>='2020-01-01' AND DFECHA<='2020-31-03' 



GROUP BY DALMACEN
