SELECT
DALMACEN AS SUCURSAL,
CATDESCR AS 'NOMBRE SUCURSAL',
SUM(AICANTF) AS PIEZAS,
SUM(ROUND((AICOSTO * AICANTF * 1.16),2)) AS 'COSTO TOTAL CON IVA',
SUM(ROUND((AICANTF*AIPRECIO)+(IF(IPORCIVA=0,(AICANTF*AIPRECIO)*((DPORCIVA/100)),0)),2)) AS 'PRECIO TOTAL CON IVA',
SUM(ROUND((AICANTF*AIPRECIO)+(IF(IPORCIVA=0,(AICANTF*AIPRECIO)*((DPORCIVA/100)),0)),2))-SUM(ROUND((AICOSTO * AICANTF * 1.16),2)) AS UTILIDAD,
(SUM(ROUND((AICANTF*AIPRECIO)+(IF(IPORCIVA=0,(AICANTF*AIPRECIO)*((DPORCIVA/100)),0)),2))-SUM(ROUND((AICOSTO * AICANTF * 1.16),2))) / (SUM(ROUND((AICANTF*AIPRECIO)+(IF(IPORCIVA=0,(AICANTF*AIPRECIO)*((DPORCIVA/100)),0)),2))) AS '%',

DFECHA AS FECHA






FROM FAXINV


LEFT JOIN FDOC ON FDOC.DSEQ=FAXINV.DSEQ

LEFT JOIN FINV ON FINV.ISEQ=FAXINV.ISEQ

LEFT JOIN FCLI ON FCLI.CLISEQ=FDOC.CLISEQ

LEFT JOIN FUNIDAD ON FUNIDAD.UCOD=FINV.IUM

LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FDOC.DALMACEN

LEFT JOIN FAG ON FAG.AGTNUM = FDOC.DPAR1

WHERE DITIPMV='T' AND (DFECHA>='2020-03-01' AND DFECHA<='2020-03-23')

AND DMULTICIA <4

GROUP BY DALMACEN, DFECHA