SELECT
IF(CATDESCR='IBUSHAK/MERCADO LIBRE','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE TOXIC','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE FULL','MERCADO LIBRE',
IF(CATDESCR='AMAZON COMER','AMAZON',
IF(CATDESCR='AMAZON EN CEDIS','AMAZON',
IF(CATDESCR='ALMACEN B2B LEKRASH','SHOPIFY',
CATDESCR
)))))) AS TIENDA,
ROUND(SUM(AICOSTO*AICANTF),2) AS 'COSTO TOTAL'



FROM FAXINV


LEFT JOIN FDOC ON FDOC.DSEQ=FAXINV.DSEQ
LEFT JOIN FINV ON FINV.ISEQ=FAXINV.ISEQ
LEFT JOIN FCLI ON FCLI.CLISEQ=FDOC.CLISEQ
LEFT JOIN FUNIDAD ON FUNIDAD.UCOD=FINV.IUM
LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FDOC.DALMACEN
LEFT JOIN FAG ON FAG.AGTNUM = FDOC.DPAR1
LEFT JOIN FFAM AS FAM1 ON FAM1.FAMTNUM=FINV.IFAM1
LEFT JOIN FFAM AS FAM2 ON FAM2.FAMTNUM=FINV.IFAM2
LEFT JOIN FFAM AS FAM3 ON FAM3.FAMTNUM=FINV.IFAM3
LEFT JOIN FFAM AS FAM4 ON FAM4.FAMTNUM=FINV.IFAM4
LEFT JOIN FFAM AS FAM5 ON FAM5.FAMTNUM=FINV.IFAM5
LEFT JOIN FFAM AS FAM6 ON FAM6.FAMTNUM=FINV.IFAM6
LEFT JOIN FFAM AS FAM7 ON FAM7.FAMTNUM=FINV.IFAM7
LEFT JOIN FFAM AS FAM8 ON FAM8.FAMTNUM=FINV.IFAM8
LEFT JOIN FFAM AS FAM9 ON FAM9.FAMTNUM=FINV.IFAM9
LEFT JOIN FFAM AS FAMA ON FAMA.FAMTNUM=FINV.IFAMA



WHERE (DITIPMV='F' OR DITIPMV='T' OR DITIPMV='FL' OR DITIPMV='FX'OR   DITIPMV='TL'OR DITIPMV='NL'OR DITIPMV='TC')

AND DFECHA>='2022-01-08' AND DFECHA<='2022-02-08'

AND DALMACEN <>0

GROUP BY (IF(CATDESCR='IBUSHAK/MERCADO LIBRE','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE TOXIC','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE FULL','MERCADO LIBRE',
IF(CATDESCR='AMAZON COMER','AMAZON',
IF(CATDESCR='AMAZON EN CEDIS','AMAZON',
IF(CATDESCR='ALMACEN B2B LEKRASH','SHOPIFY',
CATDESCR
)))))))