SELECT
'Ventas' AS clas,
IEAN AS EAN,
ICOD AS MODELO,
IDESCR AS DESCRIPCION,
FAM2.FAMDESCR AS DEPARTAMENTO,
AICANTF AS pzas,
AICOSTO AS COSTO,
AICOSTO * AICANTF AS COSTO_TOTAL,
AIPRECIO AS PRECIO,
AIPRECIO * 1.16 AS 'Precio con IVA',
AIPRECIO * 1.16 AS PRECIO_C_IVA,ROUND((AICANTF*AIPRECIO)+(IF(IPORCIVA=0,(AICANTF*AIPRECIO)*((DPORCIVA/100)),0)),2)AS PRECIO_TOTAL,
FAM1.FAMDESCR AS PROVEEDOR,
FAM3.FAMDESCR AS TIPO,
FAM4.FAMDESCR AS SUBTIPO,
FAM5.FAMDESCR AS PERSONAJE,
FAM6.FAMDESCR AS TRIMESTRE,
FAM7.FAMDESCR AS DISEÑADOR,
FAM8.FAMDESCR AS LICENCIA,
FAM9.FAMDESCR AS TIPO_DE_LICENCIA,
IF(CATDESCR='IBUSHAK/MERCADO LIBRE','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE TOXIC','MERCADO LIBRE',
IF(CATDESCR='MERCADO LIBRE FULL','MERCADO LIBRE',
IF(CATDESCR='AMAZON COMER','AMAZON',
IF(CATDESCR='AMAZON EN CEDIS','AMAZON',
IF(CATDESCR='ALMACEN B2B LEKRASH','SHOPIFY',
CATDESCR
)))))) AS TIENDA,
DFECHA AS FECHA, 
CATCONTACTO  AS  CLASIFICA_ALMACEN,
IF(DALMACEN < 100, "BOUTIQUES", IF(DALMACEN <303,"MAYOREO" ,IF(DALMACEN <503,"FRANQUICIAS", IF(DALMACEN =909,"B2C",IF(DALMACEN =905,"B2B",IF(DALMACEN =919,"AMAZON",'VENTA BODEGAS')))))) AS 'Canal de venta',
SUBSTRING(ICOD,1,9)AS MODELO_PADRE,
FAM2.FAMDESCR AS 'NUEVO DEPTO',
FAM3.FAMDESCR AS 'NUEVO TIPO',
FAMA.FAMDESCR AS OFERTA,
IF(FAMA.FAMDESCR='SIN OFERTA','Linea','Rebaja') as 'Tabla de acción'




FROM FAXINV


LEFT JOIN FDOC ON FDOC.DSEQ=FAXINV.DSEQ

LEFT JOIN FINV ON FINV.ISEQ=FAXINV.ISEQ

LEFT JOIN FCLI ON FCLI.CLISEQ=FDOC.CLISEQ

LEFT JOIN FUNIDAD ON FUNIDAD.UCOD=FINV.IUM

LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FAXINV.AIALMACEN

LEFT JOIN FAG ON FAG.AGTNUM = FDOC.DPAR1
LEFT JOIN FFAM AS FAM1 ON FAM1.FAMTNUM=FINV.IFAM1
LEFT JOIN FFAM AS FAM2 ON FAM2.FAMTNUM=FINV.IFAM2
LEFT JOIN FFAM AS FAM3 ON FAM3.FAMTNUM=FINV.IFAM3
LEFT JOIN FFAM AS FAM4 ON FAM4.FAMTNUM=FINV.IFAM4
LEFT JOIN FFAM AS FAM5 ON FAM5.FAMTNUM=FINV.IFAM5
LEFT JOIN FFAM AS FAM6 ON FAM6.FAMTNUM=FINV.IFAM6
LEFT JOIN FFAM AS FAM7 ON FAM7.FAMTNUM=FINV.IFAM7
LEFT JOIN FFAM AS FAM8 ON FAM8.FAMTNUM=FINV.IFAM8
LEFT JOIN FFAM AS FAM9 ON FAM9.FAMTNUM=FINV.IFAM9
LEFT JOIN FFAM AS FAMA ON FAMA.FAMTNUM=FINV.IFAMA

WHERE (DITIPMV='F' OR DITIPMV='T' OR DITIPMV='FL' OR DITIPMV='FX'OR   DITIPMV='TL'OR DITIPMV='NL'OR DITIPMV='TC')
/* VENTAS 4 SEMANAS */

 AND DFECHA>='2022-03-05' AND DFECHA<='2022-04-05'


AND ITIPO = 1