SELECT
DFECHA AS FECHA,CATDESCR AS TIENDA,
SUM(AICANTF) AS PIEZAS,
ROUND(SUM(AIPRECIO * AICANTF),2) AS VENTA_NETA,
COUNT(DISTINCT DNUM) AS TICKETS_TOTALES,
MID(DHORA,11,3) AS HORA






FROM FAXINV


LEFT JOIN FDOC ON FDOC.DSEQ=FAXINV.DSEQ

LEFT JOIN FINV ON FINV.ISEQ=FAXINV.ISEQ

LEFT JOIN FCLI ON FCLI.CLISEQ=FDOC.CLISEQ

LEFT JOIN FUNIDAD ON FUNIDAD.UCOD=FINV.IUM

LEFT JOIN FALMCAT ON  FALMCAT.CATALM = FDOC.DALMACEN

LEFT JOIN FAG ON FAG.AGTNUM = FDOC.DPAR1

WHERE DITIPMV='T' AND (DFECHA>='2020-01-13' AND DFECHA<='2020-02-09')

GROUP BY DALMACEN, DFECHA, MID(DHORA,11,3)